# Generated by Django 5.1.2 on 2024-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_contrato_presupuesto_general_de_la_nacion_pgn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='duracion_del_contrato',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
